// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6fEXCKLpeaNnTu0msRv2tISCDviWnqA',
    appId: '1:850971723130:web:ff776710d8755094f882c3',
    messagingSenderId: '850971723130',
    projectId: 'xculture-35793',
    authDomain: 'xculture-35793.firebaseapp.com',
    storageBucket: 'xculture-35793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuo6upVwqqEc3a_pmLYWxbpa38nUFeMAE',
    appId: '1:850971723130:android:9f983e129e9802cff882c3',
    messagingSenderId: '850971723130',
    projectId: 'xculture-35793',
    storageBucket: 'xculture-35793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnJdas-7tBqLxmhW4VJ3DJLsLE41_TryA',
    appId: '1:850971723130:ios:98ab596963fa1872f882c3',
    messagingSenderId: '850971723130',
    projectId: 'xculture-35793',
    storageBucket: 'xculture-35793.appspot.com',
    iosClientId: '850971723130-k6e18numdt4v50dea8mb68qidrel6933.apps.googleusercontent.com',
    iosBundleId: 'com.xculture.app',
  );
}
